# Chandrayan 3 Project Data Analysis

In [8]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [9]:
df = pd.read_csv("propulsion_module.csv")

In [10]:
df.head()

           Parameter                                     Specifications
0  Lunar Polar Orbit           From 170 x 36500 km to lunar polar orbit
1       Mission life  Carrying Lander Module & Rover upto ~100 x 100...
2          Structure                          Modified version of I-3 K
3           Dry Mass                   448.62 kg (including pressurant)
4    Propellant Mass                                         1696.39 kg

In [11]:
df

,Parameter,Specifications
0,Lunar Polar Orbit,From 170 x 36500 km to lunar polar orbit
1,Mission life,Carrying Lander Module & Rover upto ~100 x 100...
2,Structure,Modified version of I-3 K
3,Dry Mass,448.62 kg (including pressurant)
4,Propellant Mass,1696.39 kg
5,Total PM Mass,2145.01 kg
6,Power Generation,"738 W, Summer solistices and with bias"
7,Communication,S-Band Transponder (TTC) â€“ with IDSN
8,Attitude Sensors,"CASS, IRAP, Micro star sensor"
9,Propulsion System,Bi-Propellant Propulsion System (MMH + MON3)
10,undefined,undefined
11,# Lander Module dataframe,undefined
12,undefined,undefined
13,Parameter,Specifications
14,-,-
15,Mission life,1 Lunar day (14 Earth days)
16,Mass,1749.86 kg including Rover
17,Power,738 W (Winter solstice)
18,Payloads,3
19,Dimensions (mm3),2000 x 2000 x 1166
20,Communication,"ISDN, Ch-2 Orbiter, Rover"
21,Landing site,"69.367621 S, 32.348126 E"
22,undefined,undefined
23,# Rover dataframe,undefined
24,undefined,undefined
25,Parameter,Specifications
26,-,-
27,Mission Life,1 Lunar day
28,Mass,26 kg
29,Power,50 W
30,Payloads,2
31,Dimensions (mm3),917 x 750 x 397
32,Communication,Lander

In [12]:
data={
 "Parameter" :[
     "Lunar Polar Orbit",
     "Mission life",
     "Structure",
     "Dry Mass",
     "Propellant Mass",
     "Total PM Mass",
     "Power Generation",
     "Communication",
     "Attitude Sensors",
     "Propulsion System"
 ],
    "Specifications":[
"From 170 x 36500 km to lunar polar orbit",
"Carrying Lander Module & Rover upto ~100 x 100 km launch injection.",
"Modified version of I-3 K",
"448.62 kg (including pressurant)",
"1696.39 kg",
"2145.01 kg",
"738 W, Summer solistices and with bias",
"S-Band Transponder (TTC) â€“ with IDSN",
"CASS, IRAP, Micro star sensor",
"Bi-Propellant Propulsion System (MMH + MON3)"
    ]  
     
}

In [13]:
df=pd.DataFrame(data)

In [14]:
df

           Parameter                                     Specifications
0  Lunar Polar Orbit           From 170 x 36500 km to lunar polar orbit
1       Mission life  Carrying Lander Module & Rover upto ~100 x 100...
2          Structure                          Modified version of I-3 K
3           Dry Mass                   448.62 kg (including pressurant)
4    Propellant Mass                                         1696.39 kg
5      Total PM Mass                                         2145.01 kg
6   Power Generation             738 W, Summer solistices and with bias
7      Communication               S-Band Transponder (TTC) â€“ with IDSN
8   Attitude Sensors                      CASS, IRAP, Micro star sensor
9  Propulsion System       Bi-Propellant Propulsion System (MMH + MON3)

In [15]:
lander_df=pd.DataFrame(data)

In [26]:
data={
 "Parameter" :[
     "Mission life",
     "Mass",
     "Power",
     "Payloads",
     "Dimensions (mm3)",
     "Communication",
     "Landing site"
 ],
    "Specifications":[
"1 Lunar day (14 Earth days)",
"1749.86 kg including Rover",
"738 W (Winter solstice)",
"448.62 kg (including pressurant)",
"3",
"2000 x 2000 x 1166",
"ISDN, Ch-2 Orbiter, Rover",
"69.367621 S, 32.348126 E"
    ]  
     
}

In [27]:
lander_df=pd.DataFrame(data)

ValueError: All arrays must be of the same length

In [28]:
lander_df

           Parameter                                     Specifications
0  Lunar Polar Orbit           From 170 x 36500 km to lunar polar orbit
1       Mission life  Carrying Lander Module & Rover upto ~100 x 100...
2          Structure                          Modified version of I-3 K
3           Dry Mass                   448.62 kg (including pressurant)
4    Propellant Mass                                         1696.39 kg
5      Total PM Mass                                         2145.01 kg
6   Power Generation             738 W, Summer solistices and with bias
7      Communication               S-Band Transponder (TTC) â€“ with IDSN
8   Attitude Sensors                      CASS, IRAP, Micro star sensor
9  Propulsion System       Bi-Propellant Propulsion System (MMH + MON3)

In [29]:
import re

In [30]:
def extract_numerical_value(spec):
numeric_pattern = r'(\d+(\.\d+)?)'
custom_numeric_pattern = r"[-+]?[.]?[\d]+(?:,\d\d\d)*[\.]?\d*(?:[eE][-+]?\d+)?"
combined_pattern = f"({numeric_pattern}|{custom_numeric_pattern})"
matches = re.findall(combined_pattern, spec)
if matches:
return float(matches[0][0])
else:
return None

IndentationError: expected an indented block after function definition on line 1 (3450586842.py, line 2)

In [21]:
lander_df["Numerical Value"]=lander_df["Specifications"].apply(extract_numerical_value)

NameError: name 'extract_numerical_value' is not defined

In [22]:
lander_df

           Parameter                                     Specifications
0  Lunar Polar Orbit           From 170 x 36500 km to lunar polar orbit
1       Mission life  Carrying Lander Module & Rover upto ~100 x 100...
2          Structure                          Modified version of I-3 K
3           Dry Mass                   448.62 kg (including pressurant)
4    Propellant Mass                                         1696.39 kg
5      Total PM Mass                                         2145.01 kg
6   Power Generation             738 W, Summer solistices and with bias
7      Communication               S-Band Transponder (TTC) â€“ with IDSN
8   Attitude Sensors                      CASS, IRAP, Micro star sensor
9  Propulsion System       Bi-Propellant Propulsion System (MMH + MON3)